// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrsbbccwxkcqeueeecms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyc2JiY2N3eGtjcWV1ZWVlY21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODc3MDIsImV4cCI6MjA2NTQ2MzcwMn0.VFAGjthDpRp37BIWY7ApjvHRPYfzEweIq17yKmGkRyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);